// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FullyConnected.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FullyConnected.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sv_cl_messages {

namespace {

const ::google::protobuf::Descriptor* FullyConnected_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FullyConnected_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FullyConnected_2eproto() {
  protobuf_AddDesc_FullyConnected_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FullyConnected.proto");
  GOOGLE_CHECK(file != NULL);
  FullyConnected_descriptor_ = file->message_type(0);
  static const int FullyConnected_offsets_[1] = {
  };
  FullyConnected_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FullyConnected_descriptor_,
      FullyConnected::default_instance_,
      FullyConnected_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FullyConnected));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FullyConnected_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FullyConnected_descriptor_, &FullyConnected::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FullyConnected_2eproto() {
  delete FullyConnected::default_instance_;
  delete FullyConnected_reflection_;
}

void protobuf_AddDesc_FullyConnected_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024FullyConnected.proto\022\016sv_cl_messages\"\020"
    "\n\016FullyConnected", 56);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FullyConnected.proto", &protobuf_RegisterTypes);
  FullyConnected::default_instance_ = new FullyConnected();
  FullyConnected::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FullyConnected_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FullyConnected_2eproto {
  StaticDescriptorInitializer_FullyConnected_2eproto() {
    protobuf_AddDesc_FullyConnected_2eproto();
  }
} static_descriptor_initializer_FullyConnected_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

FullyConnected::FullyConnected()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sv_cl_messages.FullyConnected)
}

void FullyConnected::InitAsDefaultInstance() {
}

FullyConnected::FullyConnected(const FullyConnected& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sv_cl_messages.FullyConnected)
}

void FullyConnected::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FullyConnected::~FullyConnected() {
  // @@protoc_insertion_point(destructor:sv_cl_messages.FullyConnected)
  SharedDtor();
}

void FullyConnected::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FullyConnected::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FullyConnected::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FullyConnected_descriptor_;
}

const FullyConnected& FullyConnected::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FullyConnected_2eproto();
  return *default_instance_;
}

FullyConnected* FullyConnected::default_instance_ = NULL;

FullyConnected* FullyConnected::New() const {
  return new FullyConnected;
}

void FullyConnected::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FullyConnected::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sv_cl_messages.FullyConnected)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:sv_cl_messages.FullyConnected)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sv_cl_messages.FullyConnected)
  return false;
#undef DO_
}

void FullyConnected::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sv_cl_messages.FullyConnected)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sv_cl_messages.FullyConnected)
}

::google::protobuf::uint8* FullyConnected::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sv_cl_messages.FullyConnected)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sv_cl_messages.FullyConnected)
  return target;
}

int FullyConnected::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FullyConnected::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FullyConnected* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FullyConnected*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FullyConnected::MergeFrom(const FullyConnected& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FullyConnected::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FullyConnected::CopyFrom(const FullyConnected& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FullyConnected::IsInitialized() const {

  return true;
}

void FullyConnected::Swap(FullyConnected* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FullyConnected::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FullyConnected_descriptor_;
  metadata.reflection = FullyConnected_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sv_cl_messages

// @@protoc_insertion_point(global_scope)
