// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetTables.proto

#ifndef PROTOBUF_NetTables_2eproto__INCLUDED
#define PROTOBUF_NetTables_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace sv_cl_messages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_NetTables_2eproto();
void protobuf_AssignDesc_NetTables_2eproto();
void protobuf_ShutdownFile_NetTables_2eproto();

class NetTables;
class NetTables_Table;

// ===================================================================

class NetTables_Table : public ::google::protobuf::Message {
 public:
  NetTables_Table();
  virtual ~NetTables_Table();

  NetTables_Table(const NetTables_Table& from);

  inline NetTables_Table& operator=(const NetTables_Table& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetTables_Table& default_instance();

  void Swap(NetTables_Table* other);

  // implements Message ----------------------------------------------

  NetTables_Table* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetTables_Table& from);
  void MergeFrom(const NetTables_Table& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:sv_cl_messages.NetTables.Table)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  friend void  protobuf_AddDesc_NetTables_2eproto();
  friend void protobuf_AssignDesc_NetTables_2eproto();
  friend void protobuf_ShutdownFile_NetTables_2eproto();

  void InitAsDefaultInstance();
  static NetTables_Table* default_instance_;
};
// -------------------------------------------------------------------

class NetTables : public ::google::protobuf::Message {
 public:
  NetTables();
  virtual ~NetTables();

  NetTables(const NetTables& from);

  inline NetTables& operator=(const NetTables& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetTables& default_instance();

  void Swap(NetTables* other);

  // implements Message ----------------------------------------------

  NetTables* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetTables& from);
  void MergeFrom(const NetTables& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef NetTables_Table Table;

  // accessors -------------------------------------------------------

  // repeated .sv_cl_messages.NetTables.Table tables = 1;
  inline int tables_size() const;
  inline void clear_tables();
  static const int kTablesFieldNumber = 1;
  inline const ::sv_cl_messages::NetTables_Table& tables(int index) const;
  inline ::sv_cl_messages::NetTables_Table* mutable_tables(int index);
  inline ::sv_cl_messages::NetTables_Table* add_tables();
  inline const ::google::protobuf::RepeatedPtrField< ::sv_cl_messages::NetTables_Table >&
      tables() const;
  inline ::google::protobuf::RepeatedPtrField< ::sv_cl_messages::NetTables_Table >*
      mutable_tables();

  // @@protoc_insertion_point(class_scope:sv_cl_messages.NetTables)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::sv_cl_messages::NetTables_Table > tables_;
  friend void  protobuf_AddDesc_NetTables_2eproto();
  friend void protobuf_AssignDesc_NetTables_2eproto();
  friend void protobuf_ShutdownFile_NetTables_2eproto();

  void InitAsDefaultInstance();
  static NetTables* default_instance_;
};
// ===================================================================


// ===================================================================

// NetTables_Table

// required string name = 1;
inline bool NetTables_Table::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetTables_Table::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetTables_Table::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetTables_Table::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& NetTables_Table::name() const {
  // @@protoc_insertion_point(field_get:sv_cl_messages.NetTables.Table.name)
  return *name_;
}
inline void NetTables_Table::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:sv_cl_messages.NetTables.Table.name)
}
inline void NetTables_Table::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:sv_cl_messages.NetTables.Table.name)
}
inline void NetTables_Table::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sv_cl_messages.NetTables.Table.name)
}
inline ::std::string* NetTables_Table::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:sv_cl_messages.NetTables.Table.name)
  return name_;
}
inline ::std::string* NetTables_Table::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void NetTables_Table::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:sv_cl_messages.NetTables.Table.name)
}

// -------------------------------------------------------------------

// NetTables

// repeated .sv_cl_messages.NetTables.Table tables = 1;
inline int NetTables::tables_size() const {
  return tables_.size();
}
inline void NetTables::clear_tables() {
  tables_.Clear();
}
inline const ::sv_cl_messages::NetTables_Table& NetTables::tables(int index) const {
  // @@protoc_insertion_point(field_get:sv_cl_messages.NetTables.tables)
  return tables_.Get(index);
}
inline ::sv_cl_messages::NetTables_Table* NetTables::mutable_tables(int index) {
  // @@protoc_insertion_point(field_mutable:sv_cl_messages.NetTables.tables)
  return tables_.Mutable(index);
}
inline ::sv_cl_messages::NetTables_Table* NetTables::add_tables() {
  // @@protoc_insertion_point(field_add:sv_cl_messages.NetTables.tables)
  return tables_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::sv_cl_messages::NetTables_Table >&
NetTables::tables() const {
  // @@protoc_insertion_point(field_list:sv_cl_messages.NetTables.tables)
  return tables_;
}
inline ::google::protobuf::RepeatedPtrField< ::sv_cl_messages::NetTables_Table >*
NetTables::mutable_tables() {
  // @@protoc_insertion_point(field_mutable_list:sv_cl_messages.NetTables.tables)
  return &tables_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sv_cl_messages

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NetTables_2eproto__INCLUDED
