// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Noop.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Noop.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace messages {

namespace {

const ::google::protobuf::Descriptor* Noop_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Noop_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Noop_2eproto() {
  protobuf_AddDesc_Noop_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Noop.proto");
  GOOGLE_CHECK(file != NULL);
  Noop_descriptor_ = file->message_type(0);
  static const int Noop_offsets_[1] = {
  };
  Noop_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Noop_descriptor_,
      Noop::default_instance_,
      Noop_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Noop, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Noop, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Noop));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Noop_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Noop_descriptor_, &Noop::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Noop_2eproto() {
  delete Noop::default_instance_;
  delete Noop_reflection_;
}

void protobuf_AddDesc_Noop_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nNoop.proto\022\010messages\"\006\n\004Noop", 30);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Noop.proto", &protobuf_RegisterTypes);
  Noop::default_instance_ = new Noop();
  Noop::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Noop_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Noop_2eproto {
  StaticDescriptorInitializer_Noop_2eproto() {
    protobuf_AddDesc_Noop_2eproto();
  }
} static_descriptor_initializer_Noop_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

Noop::Noop()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:messages.Noop)
}

void Noop::InitAsDefaultInstance() {
}

Noop::Noop(const Noop& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:messages.Noop)
}

void Noop::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Noop::~Noop() {
  // @@protoc_insertion_point(destructor:messages.Noop)
  SharedDtor();
}

void Noop::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Noop::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Noop::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Noop_descriptor_;
}

const Noop& Noop::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Noop_2eproto();
  return *default_instance_;
}

Noop* Noop::default_instance_ = NULL;

Noop* Noop::New() const {
  return new Noop;
}

void Noop::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Noop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messages.Noop)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:messages.Noop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messages.Noop)
  return false;
#undef DO_
}

void Noop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messages.Noop)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:messages.Noop)
}

::google::protobuf::uint8* Noop::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages.Noop)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messages.Noop)
  return target;
}

int Noop::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Noop::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Noop* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Noop*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Noop::MergeFrom(const Noop& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Noop::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Noop::CopyFrom(const Noop& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Noop::IsInitialized() const {

  return true;
}

void Noop::Swap(Noop* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Noop::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Noop_descriptor_;
  metadata.reflection = Noop_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages

// @@protoc_insertion_point(global_scope)
